name: mobile_app
description: "Shareholder Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  provider: ^6.1.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/ 